name: DotNet Test

on:
  workflow_call:
    inputs:
      test-timeout:
        required: false
        type: number
        default: 10

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        timeout-minutes: ${{ inputs.test-timeout }}
        run: |
          dotnet test
